                                   
                                   
                                    <option value="" disabled>Seleccionar países</option>
                                    <option value="AF">Afganistán</option>
                                    <option value="AL">Albania</option>
                                    <option value="DE">Alemania</option>
                                    <option value="AD">Andorra</option>
                                    <option value="AO">Angola</option>
                                    <!-- <option value="Antigua y Barbuda">Antigua y Barbuda</option> -->
                                    <option value="SA">Arabia Saudita</option>
                                    <option value="DZ">Argelia</option>
                                    <option value="AR">Argentina</option>
                                    <option value="AM">Armenia</option>
                                    <option value="AU">Australia</option>
                                    <option value="AT">Austria</option>
                                    <option value="AZ">Azerbaiyán</option>
                                    <option value="BS">Bahamas</option>
                                    <option value="BH">Bahrein</option>
                                    <option value="BD">Bangladesh</option>
                                    <option value="BB">Barbados</option>
                                    <option value="BY">Belarús</option>
                                    <option value="BZ">Belice</option>
                                    <option value="BJ">Benin</option>
                                    <option value="BT">Bhután</option>
                                    <option value="BO">Bolivia</option>
                                    <option value="BA">Bosnia y Herzegovina</option>
                                    <option value="BW">Botswana</option>
                                    <option value="BR">Brasil</option>
                                    <option value="BN">Brunei Darussalam</option>
                                    <option value="BG">Bulgaria</option>
                                    <option value="BF">Burkina Faso</option>
                                    <option value="BI">Burundi</option>
                                    <option value="BE">Bélgica</option>
                                    <option value="CV">Cabo Verde</option>
                                    <option value="KH">Camboya</option>
                                    <option value="CM">Camerún</option>
                                    <option value="CA">Canadá</option>
                                    <option value="TD">Chad</option>
                                    <!--<option value="Chequia">Chequia</option>-->
                                    <option value="CL">Chile</option>
                                    <option value="CN">China</option>
                                    <option value="CY">Chipre</option>
                                    <option value="CO">Colombia</option>
                                    <option value="KM">Comoras</option>
                                    <option value="CG">Congo</option>
                                    <option value="CR">Costa Rica</option>
                                    <option value="HR">Croacia</option>
                                    <option value="CU">Cuba</option>
                                    <option value="CI">Côte d'Ivoire</option>
                                    <option value="DK">Dinamarca</option>
                                    <option value="DJ">Djibouti</option>
                                    <option value="DM">Dominica</option>
                                    <option value="EC">Ecuador</option>
                                    <option value="EG">Egipto</option>
                                    <option value="SV">El Salvador</option>
                                    <option value="AE">Emiratos Árabes Unidos</option>
                                    <option value="ER">Eritrea</option>
                                    <option value="SK">Eslovaquia</option>
                                    <option value="SI">Eslovenia</option>
                                    <option value="ES">España</option>
                                    <option value="US">Estados Unidos de América</option>
                                    <option value="EE">Estonia</option>
                                    <!--<option value="Eswatini">Eswatini</option>-->
                                    <option value="ET">Etiopía</option>
                                    <option value="RU">Federación de Rusia</option>
                                    <option value="FJ">Fiji</option>
                                    <option value="PH">Filipinas</option>
                                    <option value="FI">Finlandia</option>
                                    <option value="FR">Francia</option>
                                    <option value="GA">Gabón</option>
                                    <option value="GM">Gambia</option>
                                    <option value="GE">Georgia</option>
                                    <option value="GH">Ghana</option>
                                    <option value="GD">Granada</option>
                                    <option value="GR">Grecia</option>
                                    <option value="GT">Guatemala</option>
                                    <option value="GN">Guinea</option>
                                    <option value="GQ">Guinea Ecuatorial</option>
                                    <option value="GW">Guinea-Bissau</option>
                                    <option value="GY">Guyana</option>
                                    <option value="HT">Haití</option>
                                    <option value="HN">Honduras</option>
                                    <option value="HU">Hungría</option>
                                    <option value="IN">India</option>
                                    <option value="ID">Indonesia</option>
                                    <option value="IQ">Iraq</option>
                                    <option value="IE">Irlanda</option>
                                    <option value="IR">Irán</option>
                                    <option value="IS">Islandia</option>
                                    <option value="CK">Islas Cook</option>
                                    <option value="FO">Islas Feroe</option>
                                    <option value="MH">Islas Marshall</option>
                                    <option value="IL">Israel</option>
                                    <option value="IT">Italia</option>
                                    <option value="JM">Jamaica</option>
                                    <option value="JP">Japón</option>
                                    <option value="KZ">Jordania</option>
                                    <option value="KZ">Kazajstán</option>
                                    <option value="KE">Kenya</option>
                                    <option value="KG">Kirguistán</option>
                                    <option value="KI">Kiribati</option>
                                    <option value="KW">Kuwait</option>
                                    <option value="LS">Lesotho</option>
                                    <option value="LV">Letonia</option>
                                    <option value="LR">Liberia</option>
                                    <option value="LY">Libia</option>
                                    <option value="LT">Lituania</option>
                                    <option value="LU">Luxemburgo</option>
                                    <option value="LB">Líbano</option>
                                    <option value="MK">Macedonia del Norte </option>
                                    <option value="MG">Madagascar</option>
                                    <option value="MY">Malasia</option>
                                    <option value="MW">Malawi</option>
                                    <option value="MV">Maldivas</option>
                                    <option value="MT">Malta</option>
                                    <option value="ML">Malí</option>
                                    <option value="MA">Marruecos</option>
                                    <option value="MU">Mauricio</option>
                                    <option value="MR">Mauritania</option>
                                    <option value="FM">Micronesia</option>
                                    <option value="MN">Mongolia</option>
                                    <option value="ME">Montenegro</option>
                                    <option value="MZ">Mozambique</option>
                                    <option value="MM">Myanmar</option>
                                    <option value="MX">México</option>
                                    <option value="MC">Mónaco</option>
                                    <option value="NA">Namibia</option>
                                    <option value="NR">Nauru</option>
                                    <option value="NP">Nepal</option>
                                    <option value="NI">Nicaragua</option>
                                    <option value="NG">Nigeria</option>
                                    <option value="NU">Niue</option>
                                    <option value="NO">Noruega</option>
                                    <option value="NZ">Nueva Zelandia</option>
                                    <option value="NE">Níger</option>
                                    <option value="OM">Omán</option>
                                    <option value="PK">Pakistán</option>
                                    <option value="PW">Palau</option>
                                    <option value="PA">Panamá</option>
                                    <option value="PG">Papua Nueva Guinea</option>
                                    <option value="PY">Paraguay</option>
                                    <option value="NL">Países Bajos</option>
                                    <option value="PE">Perú</option>
                                    <option value="PL">Polonia</option>
                                    <option value="PT">Portugal</option>
                                    <option value="QA">Qatar</option>
                                    <option value="GB">Reino Unido de Gran Bretaña e Irlanda del Norte</option>
                                    <option value="CF">República Centroafricana</option>
                                    <option value="LA">República Democrática Popular Lao</option>
                                    <option value="CD">República Democrática del Congo</option>
                                    <option value="DO">República Dominicana</option>
                                    <option value="KP">República Popular Democrática de Corea</option>
                                    <option value="TZ">República Unida de Tanzanía</option> 
                                    <option value="KR">República de Corea</option>
                                    <option value="MD">República de Moldova	</option>
                                    <option value="SY">República Árabe Siria</option>
                                    <option value="RO">Rumania</option>
                                    <option value="RW">Rwanda</option>
                                    <option value="KN">Saint Kitts y Nevis</option>
                                    <option value="WS">Samoa</option>
                                    <option value="SM">San Marino</option>
                                    <option value="VC">San Vicente y las Granadinas</option>
                                    <option value="LC">Santa Lucía</option>
                                    <option value="ST">Santo Tomé y Príncipe</option>
                                    <option value="SN">Senegal</option>
                                    <option value="RS">Serbia</option>
                                    <option value="SC">Seychelles</option>
                                    <option value="SL">Sierra Leona</option>
                                    <option value="SG">Singapur</option>
                                    <option value="SO">Somalia</option>                        
                                    <option value="LK">Sri Lanka</option>
                                    <option value="ZA">Sudáfrica</option>
                                    <option value="SD">Sudán</option>
                                    <option value="SS">Sudán del Sur</option>
                                    <option value="SE">Suecia</option>
                                    <option value="CH">Suiza</option>
                                    <option value="SR">Suriname</option>
                                    <option value="TH">Tailandia</option>
                                    <option value="TJ">Tayikistán</option>
                                    <option value="TL">Timor-Leste</option>
                                    <option value="TG">Togo</option>
                                    <option value="TK">Tokelau</option>
                                    <option value="TO">Tonga</option>
                                    <option value="TT">Trinidad y Tabago</option>
                                    <option value="TM">Turkmenistán</option>
                                    <option value="TR">Turquía</option>
                                    <option value="TV">Tuvalu</option>
                                    <option value="TN">Túnez</option>
                                    <option value="UA">Ucrania</option>
                                    <option value="UG">Uganda</option>
                                    <option value="UY">Uruguay</option>
                                    <option value="UZ">Uzbekistán</option>
                                    <option value="VU">Vanuatu</option>
                                    <option value="VE">Venezuela</option>
                                    <option value="VN">Vietnam</option>
                                    <option value="YE">Yemen</option>
                                    <option value="ZM">Zambia</option>
                                    <option value="ZW">Zimbabwe</option>